### Registro de Usuario
# Probado y funcionando
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "email": "nicoabgv2@gmail.com",
    "password": "12345678"
}

### Validación del Email
# Probado y funcionando
PUT http://localhost:3000/api/users/validate-email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

{
    "code": "600355"
}

### Login de Usuario
# Probado y funcionando
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "nicoabgv@email.com",
    "password": "12345678"
}

### Onboarding (Datos Personales)
# Probado y funcionando
PUT http://localhost:3000/api/users/onboarding/personal-info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

{
    "name": "Nico",
    "lastName": "Prueba",
    "nif": "12345678X"
}

### Onboarding (Datos de la Compañía)
# Probado y funcionando
PUT http://localhost:3000/api/users/onboarding/company-info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

{
    "name": "Compañia de Nico",
    "cif": "B12345678",
    "address": "Calle Mallorca 16"
}

### Subida de Logo en Local
POST http://localhost:3000/api/storage/local
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="logo.png"
Content-Type: image/png

### Obtener Perfil del Usuario
# Probado y funcionando
GET http://localhost:3000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

### Restaurar usuario soft delete
# Probado y funcionando
PATCH http://localhost:3000/api/users/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

### Eliminar Usuario (Hard Delete)
# Probado y funcionando
DELETE http://localhost:3000/api/users/delete?type=hard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

### Eliminar Usuario (Soft Delete)
# Probado y funcionando
DELETE http://localhost:3000/api/users/delete?type=soft
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

### Solicitar recuperación de contraseña
# Probado y funcionando
POST http://localhost:3000/api/users/request-password-reset
Content-Type: application/json

{
    "email": "nicoabgv@email.com"
}

### Restablecer contraseña
# Probado y funcionando
POST http://localhost:3000/api/users/reset-password
Content-Type: application/json

{
    "email": "nicoabgv@email.com",
    "code": "788606",
    "password": "1234567890"
}

### Invitar a un compañero
# Probado y funcionando
POST http://localhost:3000/api/users/invite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

{
    "email": "nuevo-invitado@email.com"
}

### Registro del invitado
# Probado y funcionando
POST http://localhost:3000/api/users/register-invited
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im51ZXZvLWludml0YWRvQGVtYWlsLmNvbSIsInJvbGUiOiJndWVzdCIsImlhdCI6MTc0NzY0OTgxOSwiZXhwIjoxNzQ3NzM2MjE5fQ.jJpE6EBhcPAmtUdh1qKS81lP_zVNvXScg70oRN5cBMg",
    "password": "passwordSeguro123"
}

################################################################################
# Endpoints de Clientes
################################################################################

### Crear Cliente
# Probado y funcionando
POST http://localhost:3000/api/clients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

{
  "name": "Clientes Ejemplo",
  "nif": "12345678B",
  "email": "clienteA@email.com",
  "phone": "612345678",
  "address": "Calle Cliente 2"
}

### Obtener todos los Clientes
# Probado y funcionando
GET http://localhost:3000/api/clients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

### Soft Delete Cliente
# Probado y funcionando
DELETE http://localhost:3000/api/clients/682b054a834aad68eccacba2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

### Restaurar Cliente
# Probado y funcionando
PATCH http://localhost:3000/api/clients/682b054a834aad68eccacba2/recover
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

### Ver clientes archivados
# Probado y funcionando
GET http://localhost:3000/api/clients/archived
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

### Hard Delete Cliente
# Probado y funcionando
DELETE http://localhost:3000/api/clients/682b054a834aad68eccacba2?type=hard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

################################################################################
# Endpoints de Proyectos
################################################################################

### Crear Proyecto
# Probado y funcionando
POST http://localhost:3000/api/projects
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

{
  "name": "Proyecto Prueba",
  "description": "Proyecto para Nico de prueba",
  "client": "682b06a6834aad68eccacbc7"
}

### Obtener proyecto por ID
# Probado y funcionando
GET http://localhost:3000/api/projects/682b06c6834aad68eccacbcb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

### Obtener todos los Proyectos
# Probado y funcionando
GET http://localhost:3000/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk


### Actualizar Proyecto
# Probado y funcionando
PUT http://localhost:3000/api/projects/682b06c6834aad68eccacbcb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

{
  "name": "Proyecto Actualizado",
  "description": "Descripción nueva",
  "client": "67eea6df550f81f679734257"
}

###Soft Delete Proyecto
# Probado y funcionando
DELETE http://localhost:3000/api/projects/682b06c6834aad68eccacbcb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

### Hard Delete Proyecto
# Probado y funcionando
DELETE http://localhost:3000/api/projects/682b06c6834aad68eccacbcb?type=hard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

### Ver archivados
# Probado y funcionando
GET http://localhost:3000/api/projects/archived
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk


### Recuperar proyecto archivado
# Probado y funcionando
PATCH http://localhost:3000/api/projects/682b06c6834aad68eccacbcb/recover
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk


################################################################################
# Endpoints de Albaranes
################################################################################

### Crear Albarán (horas)
# Probado y funcionando
POST http://localhost:3000/api/delivery-notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

{
  "type": "hours",
  "project": "682b0769834aad68eccacbf2",
  "persons": [
    { "name": "Técnico 1", "hours": 5 },
    { "name": "Técnico 2", "hours": 3 }
  ]
}

### Crear Albarán (materiales)
# Probado y funcionando
POST http://localhost:3000/api/delivery-notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

{
  "type": "materials",
  "project": "682b0769834aad68eccacbf2",
  "materials": [
    { "name": "Cemento", "quantity": 10 },
    { "name": "Ladrillos", "quantity": 200 }
  ]
}


### Crear Albarán (mixto)
# Probado y funcionando
POST http://localhost:3000/api/delivery-notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

{
  "type": "mixed",
  "project": "682b0769834aad68eccacbf2",
  "persons": [
    { "name": "Técnico 1", "hours": 4 }
  ],
  "materials": [
    { "name": "Hormigón", "quantity": 5 }
  ]
}

### Obtener todos los Albaranes
# Probado y funcionando
GET http://localhost:3000/api/delivery-notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

### Obtener un Albarán por ID
# Probado y funcionando
GET http://localhost:3000/api/delivery-notes/682b0775834aad68eccacbf6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

### Borrar un Albarán (solo si no está firmado)
# Probado y funcionando
DELETE http://localhost:3000/api/delivery-notes/682b0782834aad68eccacbfc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk

### Firmar un albarán (subir imagen)
PATCH http://localhost:3000/api/delivery-notes/682b0782834aad68eccacbfc/sign
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="signature"; filename="firma.png"
Content-Type: image/png

< ./firma.png
--boundary123--

### Descargar PDF de un Albarán
# Probado y funcionando
GET http://localhost:3000/api/delivery-notes/pdf/682b0782834aad68eccacbfc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MmIwNGJlODM0YWFkNjhlY2NhY2I4NiIsImlhdCI6MTc0NzY0OTcyNywiZXhwIjoxNzQ3NjUzMzI3fQ.Pe9Md6sY5TXQFQ_kg4xckrOfGyH633ioHHACM7Gbnmk